@host=http://localhost:8080
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiYmFkc0B1c2VyLmNvbSIsIm5hbWUiOm51bGwsImlkIjoxfSwiaWF0IjoxNzU5NjQyNDEzLCJleHAiOjE3NTk3Mjg4MTN9.-yiswB_Y_8ENM9uKbTYc4FeiXfbw4dukYpYuVcefLK4

###
POST {{host}}/v1/user/register
Content-Type: application/json

{"email":"bads@user.com","password":"hello"}

###
GET {{host}}/v1/user 
Authorization: Bearer {{token}}

###
GET {{host}}/v1/user/1
Authorization: Bearer {{token}}