@host=http://localhost:8080
# @name login
POST {{host}}/v1/auth/signin
Content-Type: application/json

{"email":"bads@user.com","password":"hello1d3"}

###
@token = {{login.response.body.token}}
@refreshToken= {{login.response.body.refreshToken}}

###
GET {{host}}/v1/sample 
Authorization: Bearer {{token}}

###
GET {{host}}/v1/auth/refreshtoken
Authorization: Bearer {{refreshToken}}

###
GET {{host}}/metrics

###
GET {{host}}/